### PR TITLE
Change Corporate identity of the website.

### PR DESCRIPTION
**Pull request by dheeraj135**
Changes:
- Change logo and favicon
- Remove Linux Foundatation from breadcrumbs
- Change mainURI and mainURL in siteconf-*.php files.(This completely disconnects the wiki page from openprinting.org.)
- Change default redirection(openpriting.org -> https://wiki.linuxfoundation.org/openprinting/start) to openprinting.github.io page.
-  Change navigation bar entries according to openprinting.github.io page.

Problems:
- There might be some important pages which needs to migrated to the new website before removing links to them.

Screenshots:
Screenshot from 2019-09-07 16-57-36

### CODE REVIEW

**Comment by dheeraj135** [comment]
@tillkamppeter Commit https://github.com/OpenPrinting/foomatic-db-webapp/pull/3/commits/5c1574570af3a0be5ab38f556ec2919a5342b730 resolves the issue https://github.com/OpenPrinting/openprinting.github.io/issues/60. Please check the commit. Previous commits of this PR are required for https://github.com/OpenPrinting/foomatic-db-webapp/pull/3/commits/5c1574570af3a0be5ab38f556ec2919a5342b730 to work.

**Comment by tillkamppeter** [comment]
I have merged your pull request now and applied it to the site, but somehow it does not correctly displayed by the server. The logo appears huge and the links are still the old ones. I have applied all changes of this merge request to the server.

**Comment by tillkamppeter** [comment]
Logo problem solved, was browser cache, problkem is that the PHP pages used are still the old ones (old link destinations).

**Comment by tillkamppeter** [comment]
I have found the problem and solved it, now the new pages are working correctly (some links are 404 still). Thank you very much.

**Pull request merged**
